name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Format check (all files)
        run: npx nx format:check --all

      - name: Lint
        run: npx nx lint file-upload

      - name: Test (coverage)
        run: npx nx test file-upload --configuration=ci

      - name: Build
        run: npx nx build file-upload
